version: '2.2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: product-store
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
